"""Conventional anomaly detection using Isolation Forest.

This module provides the baseline detector for Qypher. It takes the processed
transaction feature matrix from data_loader.py, trains an Isolation Forest model,
and returns a per-transaction anomaly result.

Important:
- This is the conventional ML detector.
- It does not use quantum-inspired logic.
- It preserves the original transaction information so the dashboard can later show
  transaction details together with the anomaly result.
"""

from __future__ import annotations

from typing import Dict, Any

import pandas as pd
from sklearn.ensemble import IsolationForest

from data_loader import get_features_for_anomaly_detection


class ConventionalAnomalyDetector:
    """Detect anomalous transactions using IsolationForest.

    Isolation Forest works by isolating unusual points in the data. Transactions
    that are far from the normal pattern are easier to isolate and therefore get a
    larger anomaly score.
    """

    def __init__(self, contamination: float = 0.08, random_state: int = 42):
        self.model = IsolationForest(
            contamination=contamination,
            random_state=random_state,
            n_estimators=200,
        )
        self.feature_columns: list[str] | None = None

    def fit(self, features: pd.DataFrame) -> "ConventionalAnomalyDetector":
        """Train the Isolation Forest model.

        Args:
            features: Model-ready feature matrix generated by data_loader.

        Returns:
            self, so the model can be reused in a clean pipeline.
        """
        self.feature_columns = list(features.columns)
        self.model.fit(features[self.feature_columns])
        return self

    def predict_transactions(self, features: pd.DataFrame, transaction_data: pd.DataFrame) -> pd.DataFrame:
        """Generate predictions for every transaction.

        Args:
            features: Prepared model feature matrix.
            transaction_data: Original transaction data, kept for dashboard display.

        Returns:
            A DataFrame with:
            - transaction_id
            - anomaly_score
            - prediction
            - prediction_label
            - original transaction details from the source data
        """
        if self.feature_columns is None:
            raise ValueError("The model must be trained before calling predict_transactions().")

        # Ensure columns are in the same order used during training.
        feature_matrix = features.reindex(columns=self.feature_columns, fill_value=0)

        # IsolationForest returns:
        #   1 for normal observations
        #  -1 for anomalies
        predictions = self.model.predict(feature_matrix)

        # The score_samples() output is naturally lower for anomalies and higher for
        # normal transactions. We invert it so the score becomes easier to understand:
        # - larger positive anomaly_score = more unusual transaction
        # - smaller values are closer to normal behavior
        anomaly_scores = -self.model.score_samples(feature_matrix)

        prediction_df = pd.DataFrame({
            "transaction_id": transaction_data["transaction_id"].values,
            "anomaly_score": anomaly_scores,
            "prediction": predictions,
        })

        prediction_df["prediction_label"] = prediction_df["prediction"].map({
            1: "NORMAL",
            -1: "ANOMALY",
        })

        # Merge back the original transaction metadata to preserve everything needed
        # later by the dashboard and the response layer.
        result = transaction_data.merge(prediction_df, on="transaction_id", how="left")

        return result[[
            "transaction_id",
            "amount",
            "location",
            "device_id",
            "anomaly_score",
            "prediction",
            "prediction_label",
        ]].copy()


def detect_conventional_anomalies(raw_transaction_df: pd.DataFrame) -> pd.DataFrame:
    """Run the conventional detector end-to-end on raw transaction data.

    This function is the clean public interface for the rest of the project.
    It gets the processed features from data_loader.py, trains the model, and
    returns one result row per transaction.

    Args:
        raw_transaction_df: Raw CSV data read from transactions.csv.

    Returns:
        A DataFrame containing one row per transaction with:
            - transaction_id
            - amount
            - location
            - device_id
            - anomaly_score
            - prediction
            - prediction_label
    """
    prepared = get_features_for_anomaly_detection(raw_transaction_df)
    transaction_data = prepared["transaction_data"].copy()
    feature_matrix = prepared["features"].copy()
    feature_matrix = feature_matrix.select_dtypes(include=["number"]).copy()

    if feature_matrix.empty:
        raise ValueError("No numeric model features were produced for anomaly detection.")

    detector = ConventionalAnomalyDetector(contamination=0.08, random_state=42)
    detector.fit(feature_matrix)

    return detector.predict_transactions(feature_matrix, transaction_data)
